---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
      
      
      
---- three nodes
---- java -jar springcloud-eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
---- java -jar springcloud-eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
---- java -jar springcloud-eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer3